### PR TITLE
20164910 own branch

### PR DESCRIPTION
**Pull request by 20164910**
Sup guys. 
I've finally added coding for the select and read file buttons. Send me your thoughts.

### CODE REVIEW

**Comment by 20154439** [comment]
I have seen the coding, It looks good to me.

**Review by 20154439 — APPROVED** [review]
I have seen the coding, it looks good to me.

**Comment by 20164910** [comment]
Ok. I will merge it asap for our user tester to test it out for any user issues.

**Comment by 20164910** [comment]
I reopened for pull request for merging purposes. No need for additional input.

**Pull request merged**
